spring.application.name=pricing-backend
spring.config.import=optional:application-secret.properties
<<<<<<< Updated upstream
spring.data.mongodb.uri=${MONGO_URI}
=======
spring.data.mongodb.uri=mongodb+srv://siddhantojha938_db_user:xynVd7F4sxJolZXn@cluster0.xumnlqu.mongodb.net/dynamic_pricing_db
>>>>>>> Stashed changes
