spring.application.name=pricing-backend
spring.data.mongodb.uri=mongodb+srv://godajm123_db_user:wpDn8lhYRAKkLVyy@dynamicpricing.xumnlqu.mongodb.net/dynamic_pricing_engine?retryWrites=true&w=majority&appName=DynamicPricing
